server:
  port: 80
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.cp: DEBUG
    me.chanjar.weixin: DEBUG
wechat:
  cp:
    corpId: ww233de79ab8418b37
    secret: n0rOq1ZyZpSZhzo1ibuw_xZvkAmjhMhH6EsKaiZjqba
    token: 111
    aesKey: 111
    agentId: 1000008